terraformignore.go
Default paths should use os.PathSeparator to be more general and friendly for our Windows-user friends.
=> Make default paths respect os.PathSeparator

slug.go, slug_test.go
Change the `Unpack` function to safely handle files and symlinks while unpacking the tarball.
Fix developed by @ryanuber @RussellRollins.
=> Fix for unsafe tar unpacking

README.md
I noticed the build badge claimed to be failing, after I merged my last PR.
We're using CircleCI now, instead of Travis.
=> Fixes CI status badge

terraformignore.go
This PR is very trivial.
#9 introduced multi-OS friendly .terraformignore feature.
The original implementation is enough, but I think it's better to use `filepath.Join` to do that.
`filepath` package is
> Package filepath implements utility routines for manipulating filename paths in a way compatible with the target operating system-defined file paths.
(ref : https://golang.org/pkg/path/filepath/
So, to support multi-OS, `filepath` helps. (and, code becomes much simple 👍
=> Use filepath.Join instead of strings.Join for os compatibility

slug.go, slug_test.go
While Terraform packing up configuration is one use of go-slug's Pack function, there are other uses not directly related to Terraform.
To that end, it'd be nice for the `.terraformignore` functionality to be optional. However, at the moment, it is not.
Even if `go-slug` user intentionally creates a blank `.terraformignore` file, the system is still "additive". The default rules are always applied.
This PR introduces a new struct, the `Packer` struct (ironically, completely unrelated to Packer the HashiCorp product).
The existing package level Pack function will keep its same function signature, but callers of `go-slug` can now create a custom Packer using functional options, which will have a simplified function signature.
One of those options will be to bypass the `.terraformignore` …
=> Allow bypassing the .terraformignore rules

terraformignore.go, terraformignore_test.go
TFE/TFC will return an error if `terraform.tfstate` is detected in the
slug that is uploaded to the remote agent. In TFE/TFC we read state from
the cloud rather than a state file, so we do not need `terraform.tfstate`
to be included in the slug.
This commit adds `terraform.tfstate` to the default exclusions list,
which is used if, and only if, there is no `.terraformignore` file
specified in the project directory. So if that file is included the
`terraform.tfstate` file WILL be included in the slug, unless of course
it is added to the `.terraformignore` file.
This gives us flexibility to have the default state file included if
needed and excluded by default.
=> Add terraform.tfstate to default exclusion list

slug.go, slug_test.go, testdata/absolute-symlink/sym, testdata/archive-dir/dangling_symlink
Fixes an issue where a dangling symlink causes the `Pack()` function to fail. In general a dangling symlink is fairly innocuous, particularly so if the symlink is pointing to a path within the "root" of the archive. With this PR , dangling symlinks are now allowed so long as their targets remain _within_ the root of the archive.
This also adds some additional tests to verify that we handle dangling symlinks on the `Unpack()` side as well, and disallows absolute symlinks from being packed into a slug, which would inevitably error on the `Unpack()` side.
Fixes #18
=> Support dangling symlinks

slug.go, slug_test.go
This allows the caller to specify any path(s) which symlinks may point to _outside_ of the slug directory. Sometimes having an absolute symlink to a file elsewhere on the system is necessary, while other times allowing such arbitrary targets on symlinks may pose security concerns. This implementation keeps the default as secure as possible, prohibiting external link targets, but allows callers to specify one or more file paths or prefixes which are allowed. It is then up to the specific application to make the determination as to what is or isn't allowed.
=> Expose option for explicitly allowing certain symlinks with external targets

README.md
This PR updates references to the default branch as part of the effort to rename the default branch to `main` across our repos.
The CI failure appears to be related to Circle <> Github permissions - it looks like we'll need to recreate the Circle SSH key.
=> update references to default branch

slug.go, slug_test.go
This fix results from a bug where if the `src` directory to pack is a symlink, the resulting tar will contain no files. This attempts to resolve the symlink (if necessary) _before_ we begin to walk and archive the contents. 
To quickly reproduce this issue with Terraform:
1. Create any working directory. Ensure that the configuration is using the `cloud` or `backend "remote"` block. Run `terraform init`. 
1. Create a symlink: `ln -s /path/to/wkdir /path/to/wkdir-symlink`
1. `cd /path/to/wkdir-symlink && terraform apply`
1. You should see an error that no configuration files were found.
=> Resolve root dir if symlink

slug.go, slug_test.go, testdata/archive-dir-absolute/_common/extra-files/bar.sh, testdata/archive-dir-absolute/_common/extra-files/foo.sh, testdata/archive-dir-absolute/_common/locals.tf, testdata/archive-dir-absolute/_common/output.tf, testdata/archive-dir-absolute/_common/versions.tf, testdata/archive-dir-absolute/dev/backend.tf, testdata/archive-dir-absolute/dev/extra-files, testdata/archive-dir-absolute/dev/locals.tf, testdata/archive-dir-absolute/dev/output.tf, testdata/archive-dir-absolute/dev/variables.tf, testdata/archive-dir-absolute/dev/versions.tf
This issue regarding dereferencing symlinks has plagued Terraform v1.3.0+ (reported for several versions [here](https://github.com/hashicorp/terraform/issues/31895)). The first issue, dereferencing symlinks whose targets resolve to symlinks _outside_ of the `src` directory was resolved in #37. The second issue, when the `src` directory itself is a symlink was resolved in #36. The last issue, and the focus of this PR, deals with normalizing paths when attempting to traverse the `src` directory. My change is simple: before attempting to traverse the `src` normalize the path representation to its absolute form. 
Big thank you to @willhughes-au and @calvinbui for providing the fixture used to test that paths are normalized. 
If you'd like to test that this works with Terraform, you will need …
=> Normalize relative paths to an absolute path

sourceaddrs/source.go, sourceaddrs/source_local.go, sourceaddrs/source_test.go, sourcebundle/diagnostics.go
We previously missed an exception for making the canonical form of a local source referring to the current directory be `"./"`, to match the parent directory form `"../"`. This logic was incorrectly requiring that it be written as `"./."`, which is silly and inconsistent with Terraform CLI's current behavior.
Now `"./"` and `"../"` are both accepted as canonical forms, and naked `"."` and `".."` are still rejected as non-canonical as before, which we do just to avoid injecting further ambiguity into this already-rather-ambiguous source address syntax so that we'll have more options for potentially expanding this microsyntax in future.
=> sourceaddrs: Use correct canonical form for current directory

sourceaddrs/source_final.go, sourceaddrs/source_final_test.go, sourceaddrs/source_registry_final.go
We need to be able to decode string representations of final sources, and the existing ParseSource function doesn't handle versioned registry source addresses. This commit introduces ParseFileSource and supporting functions for decoding final registry sources.
=> Add sourceaddrs.ParseFinalSource

sourcebundle/builder.go, sourcebundle/testdata/pkgs/terraformignore/.terraformignore
Previously, when building the source bundle, if an excluded directory had files in it, the build process would error because filepath.Walk computes the list of children for a directory before executing the walk function on that directory. Our function was deleting the directory (and all children) and then returning an error later when it tried to process (the now deleted) children.
Now, when we delete the directory we return the filepath.SkipDir directory which tells it to stop trying to recurse and it won't process the deleted children.
=> Skip processing deleted directories during sourcebundle.Build

sourcebundle/builder.go, sourcebundle/builder_test.go, sourcebundle/package_fetcher.go, sourcebundle/registry_client.go
The package fetcher and registry client interfaces previously returned only the data we currently support. This makes it difficult to add more data and metadata in future updates to this library, as each addition will be a breaking change.
This commit adds trivial wrapping types around these response values, allowing us to easily add more fields to those types when we have more data to return, without forcing a new major version.
=> sourcebundle: Improve client extensibility

sourcebundle/package_meta.go
Fixes issue with retrieving the git commit message meta when calling PackageMeta receiver method, `GitCommitMessage() string`
=> fix: PackageMeta builder excluding gitCommitMessage

sourcebundle/builder.go, sourcebundle/builder_test.go, sourcebundle/diagnostics.go
This PR removes the `Append` function from the diagnostics supported by the source bundle package.
This function accepts any argument, but will then panic if the user passes in an unsupported type. The only supported types are the `Diagnostic` type and the `Diagnostics` type, both of which can be handled normally via the inbuilt `append` function. I think this function exists solely to allow a non-compile time safe way of appending diagnostics which isn't actually a useful thing to have or support.
Note, this is a breaking change so when upgrading callers will need to update their usage of these diagnostics to use the `append` function instead of the now-removed `Append` function.
=> sourcebundle: remove the option to append anything into a diagnostic that will then panic

sourcebundle/builder.go
Replacement for https://github.com/hashicorp/go-slug/pull/67
Seems like a copy-paste error here. I think this works most of the time because packages and registrymeta are usually the same size. But, if someone loads a package directly from Github (or another source) without going through the registry this panics.
=> sourcebundle: Fix panic when RegistryMeta and Packages aren't the same size

slug.go
Deprecate option to inform users that the option will be removed in a future release of the library. The motivation is to simplify the implementation logic and prepare the adoption of [hashicorp/go-extract](https://github.com/hashicorp/go-extract).
=> Deprecate unused pack/unpack option `AllowSymlinkTarget`

internal/unpackinfo/unpackinfo.go, internal/unpackinfo/unpackinfo_test.go
Extend the check that verifies that every element in the destination path is NOT a symlink. Additionally, ensure that the extraction stays in the destination directory.
=> Adjust destination path check

internal/unpackinfo/unpackinfo.go, internal/unpackinfo/unpackinfo_test.go
Alternative to https://github.com/hashicorp/go-slug/pull/77 but using`"path/filepath"` instead of strings. 
Resolves a bug where the prefix check doesn't work on empty path.
Testing with real tarballs ([ref](https://github.com/hashicorp/security-vulnerabilities/pull/362))
=> fix: bug in prefix and suffix check using filepath

sourceaddrs/source_remote.go, sourceaddrs/source_test.go
Internal ticket: https://hashicorp.atlassian.net/browse/TF-26710
=> sourceaddrs: support query paths in github and gitlab addresses

sourceaddrs/source_remote.go, sourceaddrs/source_test.go
The source address expansion handling for shorthand URLs (GitHub, GitLab) that include a subpath is currently broken. If a valid shorthand slug includes a subpath, the user receives an incorrect format error message. This revision ensures that empty strings are excluded when building the full source address.
Example Error message
```
invalid remote source address "gitlab.com/hashicorp/stacks.git//path/to/dir?ref=v4.8.0": invalid sub-path: must be slash-separated relative path without any .. or . segments
```
=> fix(sourceaddrs): subpath handling for short-hand url expansion
